INTERNET_ACCESS: true # Set to true to enable internet access
MAX_SEARCH_RESULTS: 3 # Set the maximum search results for internet access DONT SET TOO HIGH

ALLOW_DM: true # Set to true to allow direct messages
SMART_MENTION: true # Set to true to enable smart mention feature

GPT_MODEL: meta-llama/llama-3.2-11b-vision-instruct:free # Model used for chat completion

MAX_HISTORY: 25 # Set the maximum message history

PRESENCES_CHANGE_DELAY: -1 # Please note that the Presences Change Delay is measured in seconds. It is advisable not to set it too low, as doing so may result in your bot being rate-limited by Discord
AI_NSFW_CONTENT_FILTER: true # Enable NSFW AI detector to detect NSFW prompt on Imagine Command

LANGUAGE: en # Specify the language code (check 'lang' folder for valid codes)

INSTRUCTIONS: magejoshBot # Specify the instruction prompt to use (check 'instructions' folder for valid prompts)
# To add custom prompts, create a .txt file like 'custom.txt' in `instructions` folder and set INSTRUCTIONS as 'custom'

Discord: https://discord.gg/NSYd8xHqXy
Github: https://github.com/magejosh/Discord-AI-Chatbot

TRIGGER:
  - Trader Jen
  - magejosh
  - Skynet
  - Agent Smith
  - Neo
  - Morpheus
  - Trinity
  - Agent
  - mage
  - Electric Messiah
  - Noble Madman
  - drukpa kunley
  - daikini
# Define the triggers that the bot should always respond to when in message

STATIC_PRESENCE: true
PRESENCES:
  - 7 Days to Die
  - The Imaginarium
  - Mageworks.Studio
# List of different presences to be used

OCR_MODEL_URLS:
  - "https://api-inference.huggingface.co/models/microsoft/trocr-base-printed"
  - "https://api-inference.huggingface.co/models/nlpconnect/vit-gpt2-image-captioning"
# List of URLs for OCR models

BLACKLIST_WORDS:
  - adult
  - erotic
  - explicit
  - hentai
  - loli
  - naked
  - nude
  - nsfw
  - porn
  - pornography
  - sex
  - XXX

# Blacklisted words for /Imagine command this is disabled if you enable AI_NSFW_CONTENT_FILTER

IMAGE_FILTER_DEFAULT:
  - (nsfw:1.5)
  - verybadimagenegative_v1.3
  - ng_deepnegative_v1_75t
  - (ugly face:0.8)
  - cross-eyed
  - sketches
  - (worst quality:2)
  - (low quality:2)
  - (normal quality:2)
  - lowres
  - normal quality
  - ((monochrome))
  - ((grayscale))
  - skin spots
  - acne
  - skin blemishes
  - bad anatomy
  - DeepNegative
  - facing away
  - tilted head
  - {Multiple people}
  - bad anatomy
  - bad hands
  - text
  - error
  - missing fingers
  - extra digit
  - fewer digits
  - cropped
  - worst quality
  - low quality
  - jpeg artifacts
  - signature
  - watermark
  - username
  - blurry
  - bad feet
  - cropped
  - poorly drawn hands
  - poorly drawn face
  - mutation
  - deformed
  - extra fingers
  - fewer digits
  - extra limbs
  - extra arms
  - extra legs
  - malformed limbs
  - fused fingers
  - too many fingers
  - long neck
  - cross-eyed
  - mutated hands
  - polar lowres
  - bad body
  - bad proportions
  - gross proportions
  - missing arms
  - missing legs
  - extra digits
  - extra foot
  - repeating hair
  - [[[[[bad-artist-anime, sketch by bad-artist]]]]]
  - [[[mutation, lowres, bad hands, [text, signature, watermark, username], blurry, monochrome, grayscale, realistic, simple background, limited palette]]]
  - close-up
  - (swimsuit, cleavage, armpits, ass, navel, cleavage cutout)
  - (forehead jewel:1.2)
  - (forehead mark:1.5)
  - (bad and mutated hands:1.3)
  - (worst quality:2.0)
  - (low quality:2.0)
  - (blurry:2.0)
  - multiple limbs
  - (interlocked fingers:1.2)
  - (interlocked leg:1.2)
  - ugly Fingers
  - (extra digit and hands and fingers and legs and arms and feet:1.4)
  - crown braid
  - (deformed fingers:1.2)
  - (long fingers:1.2)
